### PR TITLE
Rejects

### PR DESCRIPTION
**Pull request by BLRussell-09**

### CODE REVIEW

**Comment by aprilrochelle** [comment]
Hey Barry, I see the little badge next to the word Friends (which looks way official!), but when I click on friends, I don't see anything in the dom.

**Comment by BLRussell-09** [comment]
Yeah, once you've added a friend, the user should appear on the screen, for some reason now it only shows up if you click it twice, it's hanging somewhere but I've put finding that bug that off for a bit

**Comment by BLRussell-09** [comment]
Ok, now I see what you mean.

**Comment by aprilrochelle** [comment]
Ok, I didn't see anything at all... No way to add a friend.

**Comment by BLRussell-09** [comment]
Yeah, I had merge conflicts when I initially pushed the code, and I thought I fixed it because git let me push the PR again and told me I had no conflicts. When I opened the code again and ran grunt it told me there was a git conflict. It should work now. There's still a bug on that friend button that shows your list of friends, just click it twice and it'll show you the list, I'm not sure why its bugging out on the first click.

**Comment by aprilrochelle** [comment]
Ok cool. I can see a list of users now.  Almost there!

👍

**Pull request merged**
